name: pytest
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run pytest
